Repository yourssu/Yourssu-Scouter-Backend, pull requests merged in 2025-09, with the labels that each got.

#112 fix:#110 Google Oauth 리다이렉트 경로 mismatch
  .gitignore
  env.example
  src/main/kotlin/com/yourssu/scouter/common/application/domain/authentication/AuthenticationController.kt
  src/main/kotlin/com/yourssu/scouter/common/application/domain/authentication/OAuth2Controller.kt
  src/main/kotlin/com/yourssu/scouter/common/application/domain/authentication/OAuth2LoginRequest.kt
  src/main/kotlin/com/yourssu/scouter/common/application/support/authentication/LoginInterceptor.kt
  src/main/kotlin/com/yourssu/scouter/common/application/support/configuration/RequestLoggingFilter.kt
  src/main/kotlin/com/yourssu/scouter/common/application/support/exception/CommonExceptionHandler.kt
  src/main/kotlin/com/yourssu/scouter/common/business/domain/authentication/AuthenticationService.kt
  src/main/kotlin/com/yourssu/scouter/common/business/domain/authentication/OAuth2Service.kt
  src/main/kotlin/com/yourssu/scouter/common/implement/domain/authentication/OAuth2Handler.kt
  src/main/kotlin/com/yourssu/scouter/common/implement/support/configuration/OpenFeignConfiguration.kt
  src/main/kotlin/com/yourssu/scouter/common/implement/support/security/oauth2/GoogleOAuth2Handler.kt
  src/main/kotlin/com/yourssu/scouter/common/implement/support/security/oauth2/GoogleOAuth2Properties.kt
  src/main/resources/application-local.yml
Labels: bug

#114 [#73]; docs: swagger api 문서화 추가
  build.gradle.kts
  src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ApplicantController.kt
  src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ApplicantSyncController.kt
  src/main/kotlin/com/yourssu/scouter/common/application/domain/authentication/AuthenticationController.kt
  src/main/kotlin/com/yourssu/scouter/common/application/domain/authentication/OAuth2Controller.kt
  src/main/kotlin/com/yourssu/scouter/common/application/domain/authentication/SwaggerOAuth2Controller.kt
  src/main/kotlin/com/yourssu/scouter/common/application/domain/college/CollegeController.kt
  src/main/kotlin/com/yourssu/scouter/common/application/domain/department/DepartmentController.kt
  src/main/kotlin/com/yourssu/scouter/common/application/domain/division/DivisionController.kt
  src/main/kotlin/com/yourssu/scouter/common/application/domain/mail/MailReservationController.kt
  src/main/kotlin/com/yourssu/scouter/common/application/domain/mail/template/MailTemplateController.kt
  src/main/kotlin/com/yourssu/scouter/common/application/domain/part/PartController.kt
  src/main/kotlin/com/yourssu/scouter/common/application/domain/semester/SemesterController.kt
  src/main/kotlin/com/yourssu/scouter/common/application/support/authentication/AuthUserInfo.kt
  src/main/kotlin/com/yourssu/scouter/common/application/support/configuration/SwaggerConfiguration.kt
  src/main/kotlin/com/yourssu/scouter/common/application/support/configuration/WebConfiguration.kt
  src/main/kotlin/com/yourssu/scouter/hrms/application/domain/member/MemberController.kt
  src/main/kotlin/com/yourssu/scouter/hrms/application/domain/member/MemberSyncController.kt
  src/main/resources/application-local.yml
Labels: docs

#117 [#116]; chore: Claude code action 추가
  .github/workflows/claude-issue-comment.yml
  .github/workflows/claude-issue.yml
  .github/workflows/claude-pr.yml
Labels: deploy

#121 fix: tokenURL과 refreshURL이 환경 종속적이지 않게 변경
  src/main/kotlin/com/yourssu/scouter/common/application/support/configuration/SwaggerConfiguration.kt
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: fix

#128 [#124]; feat: 지원자의 면접 가능 시간 컬럼 추가
  src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/CreateApplicantRequest.kt
  src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/ReadApplicantResponse.kt
  src/main/kotlin/com/yourssu/scouter/ats/application/domain/applicant/UpdateApplicantRequest.kt
  src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/ApplicantDto.kt
  src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/ApplicantService.kt
  src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/CreateApplicantCommand.kt
  src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/FormResponseToApplicantProcessor.kt
  src/main/kotlin/com/yourssu/scouter/ats/business/domain/applicant/UpdateApplicantCommand.kt
  src/main/kotlin/com/yourssu/scouter/ats/implement/domain/applicant/Applicant.kt
  src/main/kotlin/com/yourssu/scouter/ats/implement/domain/applicant/ApplicantSyncMapping.kt
  src/main/kotlin/com/yourssu/scouter/ats/storage/domain/applicant/ApplicantAvailableTimeEntity.kt
  src/main/kotlin/com/yourssu/scouter/ats/storage/domain/applicant/ApplicantEntity.kt
  src/main/kotlin/com/yourssu/scouter/ats/storage/domain/applicant/ApplicantRepositoryImpl.kt
  src/main/kotlin/com/yourssu/scouter/ats/storage/domain/applicant/ApplicantSyncMappingEntity.kt
  src/main/kotlin/com/yourssu/scouter/ats/storage/domain/applicant/JpaApplicantAvailableTimeRepository.kt
  src/main/kotlin/com/yourssu/scouter/common/implement/support/configuration/PropertiesConfiguration.kt
  src/main/kotlin/com/yourssu/scouter/common/implement/support/google/GoogleFormsClient.kt
  src/main/kotlin/com/yourssu/scouter/common/implement/support/google/GoogleFormsReader.kt
  src/main/kotlin/com/yourssu/scouter/common/implement/support/google/UserResponse.kt
  src/main/kotlin/com/yourssu/scouter/common/implement/support/initialization/ApplicantAvailableTimeMap.kt
  src/main/kotlin/com/yourssu/scouter/common/implement/support/initialization/ApplicantSyncMappingData.kt
  src/main/kotlin/com/yourssu/scouter/common/implement/support/initialization/ApplicantSyncMappingInitializer.kt
  src/main/resources/applicant-available-time-map.yml
  src/main/resources/application.yml
Labels: feature, claude-review

#143 [#139]; feat: 면접 계획 생성을 위한 레포지토리 레이어 구현
  src/main/kotlin/com/yourssu/scouter/ats/implement/domain/recruiter/InterviewSchedule.kt
  src/main/kotlin/com/yourssu/scouter/ats/implement/domain/recruiter/ScheduleReader.kt
  src/main/kotlin/com/yourssu/scouter/ats/implement/domain/recruiter/ScheduleRepository.kt
  src/main/kotlin/com/yourssu/scouter/ats/implement/domain/recruiter/ScheduleWriter.kt
  src/main/kotlin/com/yourssu/scouter/ats/storage/domain/recruiter/JpaScheduleRepository.kt
  src/main/kotlin/com/yourssu/scouter/ats/storage/domain/recruiter/ScheduleEntity.kt
  src/main/kotlin/com/yourssu/scouter/ats/storage/domain/recruiter/ScheduleRepositoryImpl.kt
  src/main/kotlin/com/yourssu/scouter/ats/storage/domain/support/exception/DuplicateScheduleException.kt
Labels: feature, claude-review
